services:

  legal-service:
    build: ./legal-service
    container_name: legal-service
    ports:
      - "8082:8082"
    depends_on:
      - db
      - kafka
      - redis
    entrypoint: ["/wait-for-it.sh", "redis:6379", "--", "java", "-jar", "app.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=runtime
    networks:
      - visulaw-net

  embedding-service:
    build:
      context: ./embedding-service
      dockerfile: Dockerfile
    container_name: embedding-service
    depends_on:
      - kafka
    networks:
      - visulaw-net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9000:9000"
    # depends_on:
    #   - legal-service
    #   - embedding-service
    #   - redis
    networks:
      - visulaw-net

  auth-provider:
    build:
      context: ./auth-provider
      dockerfile: Dockerfile
    container_name: auth-provider
    ports:
      - "8081:8081"
    # depends_on:
    #   - legal-service
    #   - embedding-service
    #   - redis
    networks:
      - visulaw-net

  db:
    image: ankane/pgvector
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: visulaw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - visulaw-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - visulaw-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@visulaw.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - visulaw-net

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - visulaw-net

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - visulaw-net


volumes:
  pgdata:

networks:
  visulaw-net:
    driver: bridge

